#!/usr/bin/env python3
"""
make_selftest_gt.py -- Build a synthetic ground-truth folder from the program's
own output, in ImageJ Results format.

This is a PLUMBING test, not a correctness test. Because the "expected" values
are generated by the same code being measured, every stage passes trivially --
which is exactly the point: it proves the harness parses ImageJ exports,
identifies ROIs from labels, reshapes the grid, runs all nine stages and writes
its reports, without needing a human in Fiji first.

A real ground truth measured by hand is what actually validates the numbers.
This only validates the ruler, not the measurement.

Usage:
  python tests/make_selftest_gt.py --image <any_plate.JPG>
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
import spotting_quant as sq   # noqa: E402

BALL_RADIUS = 107.0     # protocol reading: (spot diameter + 20) / 2
MEASURE_DIAMETER = 174.0
STRAINS = sq.STRAIN_NAMES
ROW_REP1, ROW_REP2 = 3, 5   # 1-based overall rows


def results_frame(img: np.ndarray, grid: sq.Grid,
                  bg_centers: list[tuple[float, float]],
                  image_title: str) -> pd.DataFrame:
    """Emit an ImageJ-style Results table for all 53 ROIs."""
    r = grid.measure_radius
    d = float(round(2 * r))
    rows = []

    def one(label: str, cy: float, cx: float) -> None:
        bx, by = round(cx - d / 2), round(cy - d / 2)
        mean, n_px = sq._roi_mean(img, bx, by, d, d)
        y0, y1 = int(by), int(by + d)
        x0, x1 = int(bx), int(bx + d)
        patch = img[max(0, y0):y1, max(0, x0):x1]
        rows.append({
            "Label": f"{image_title}:{label}", "Area": n_px,
            "Mean": round(float(mean), 3),
            "StdDev": round(float(patch.std()), 3),
            "Min": round(float(patch.min()), 3), "Max": round(float(patch.max()), 3),
            "X": round(float(cx), 3), "Y": round(float(cy), 3),
            "BX": int(bx), "BY": int(by), "Width": int(d), "Height": int(d),
        })

    for i in range(sq.N_ROWS):
        for j in range(sq.N_COLS):
            cy, cx = grid.centers[i, j]
            one(f"spot_r{i+1}c{j+1}", cy, cx)
    for k, (cy, cx) in enumerate(bg_centers, start=1):
        one(f"bg_{k}", cy, cx)

    df = pd.DataFrame(rows)
    df.insert(0, " ", range(1, len(df) + 1))    # ImageJ's unnamed index column
    return df


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", type=Path, required=True,
                    help="Any plate image to build the self-test against. "
                         "Required: there is no sample plate in the repo, so a "
                         "default would only ever resolve to a missing file.")
    ap.add_argument("--out", type=Path, default=HERE / "gt" / "_selftest")
    args = ap.parse_args(argv)

    if not args.image.is_file():
        print(f"Image not found: {args.image}", file=sys.stderr)
        return 2
    args.out.mkdir(parents=True, exist_ok=True)

    img8 = sq.load_gray8(args.image)
    grid = sq.detect_grid(img8)
    grid.measure_radius = MEASURE_DIAMETER / 2.0
    bg_centers = sq.background_gap_centers(grid)

    # ROI geometry, in the schema load_roi_csv expects
    sq.export_rois(grid, bg_centers, args.out / "gt_rois")
    (args.out / "gt_rois.ijm").unlink(missing_ok=True)

    # Stage 1: raw 8-bit
    results_frame(img8.astype(np.float64), grid, bg_centers, args.image.name) \
        .to_csv(args.out / "gt_measurements_raw8.csv", index=False,
                encoding="utf-8-sig")

    # Stage 2: after rolling-ball subtraction
    proc, _, spread = sq.subtract_background(
        img8, ball_radius=BALL_RADIUS, bg_centers=bg_centers,
        bg_radius=grid.measure_radius, iters=1)
    results_frame(proc, grid, bg_centers, args.image.name) \
        .to_csv(args.out / "gt_measurements_rollingball.csv", index=False,
                encoding="utf-8-sig")

    # Relative growth, so S6a/S6b have something to align against
    meas = sq.measure_plate(proc, grid, bg_centers)
    rows = []
    for rep, row in ((1, ROW_REP1 - 1), (2, ROW_REP2 - 1)):
        for j in range(sq.N_COLS):
            rows.append({"treatment": "gt", "replicate": f"rep{rep}",
                         "strain_col": j + 1, "strain": STRAINS[j],
                         "raw_growth": meas.net[row, j]})
    tidy = sq.add_relative_growth(pd.DataFrame(rows), control_col=1)
    tidy[["replicate", "strain", "relative_growth"]].to_csv(
        args.out / "gt_relative_growth.csv", index=False, encoding="utf-8-sig")

    meta = [
        ("image_relpath", args.image.name),
        ("image_sha256", hashlib.sha256(args.image.read_bytes()).hexdigest()),
        ("image_width", img8.shape[1]), ("image_height", img8.shape[0]),
        ("imagej_version", "SYNTHETIC -- generated by make_selftest_gt.py"),
        ("rgb_weighted", "FALSE"), ("scale_when_converting", "TRUE"),
        ("roi_shape", "oval"), ("measure_diameter_px", MEASURE_DIAMETER),
        ("rollingball_radius_px", BALL_RADIUS),
        ("rb_light_background", "FALSE"), ("rb_sliding_paraboloid", "TRUE"),
        ("rb_disable_smoothing", "FALSE"), ("rb_preview", "FALSE"),
        ("rollingball_iterations", 1), ("bg_spread_after", round(spread, 3)),
        ("quantified_row_rep1", ROW_REP1), ("quantified_row_rep2", ROW_REP2),
        ("control_col", 1),
    ] + [(f"strain_col_{j+1}", STRAINS[j]) for j in range(sq.N_COLS)] + [
        ("operator", "make_selftest_gt.py"), ("date", "synthetic"),
        ("notes", "PLUMBING TEST ONLY -- expected values come from the same code "
                  "under test, so passing proves the harness runs, NOT that the "
                  "numbers are right."),
    ]
    pd.DataFrame(meta, columns=["key", "value"]).to_csv(
        args.out / "gt_meta.csv", index=False, encoding="utf-8-sig")

    print(f"Wrote synthetic ground truth to {args.out}")
    print(f"  background spread after subtraction: {spread:.2f} gray")
    print(f"\nNow run:\n  python tests/calibrate.py --gt {args.out} "
          f"--image {args.image}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
